### ISSUE TITLE
B003 - Desenvolver o crud de Endereço + DTO de endereço

### ISSUE THREAD

**Issue by Mateus-Gabardo** [Mateus-Gabardo/Droneseta-E-commerce-backend#3]
Desenvolver o crud de Endereço + DTO de endereço.
 **Tabela Endereço**

		|Campo: endereco_id
		|Tipo: int
		|Chave: PK
		|Descrição: Chave primária da tabela Endereço

		|Campo: logradouro
		|Tipo: varchar(255)
		|Chave:
		|Descrição: Logradouro do endereço

		|Campo: numero
		|Tipo: integer
		|Chave:
		|Descrição: Número do endereço

		|Campo: complemento
		|Tipo: varchar(255)
		|Chave:
		|Descrição: Complemento do endereço

		|Campo: bairro
		|Tipo: varchar(100)
		|Chave:
		|Descrição: Bairro do endereço

		|Campo: cidade
		|Tipo: varchar(100)
		|Chave:
		|Descrição: Cidade do endereço
		
		|Campo: estado
		|Tipo: varchar(2)
		|Chave:
		|Descrição: Estado do endereço
		
		|Campo: cep
		|Tipo: varchar(8)
		|Chave:
		|Descrição: CEP do endereço
		
		|Campo: cliente_id_fk
		|Tipo: FK
		|Chave:
		|Descrição: Chave estrangeira relacionando um endereço a um cliente

**Comment by danielkluggy** [comment]
Finished
