### ISSUE TITLE
B008 - Configurar Swagger

### ISSUE THREAD

**Issue by Mateus-Gabardo** [Mateus-Gabardo/Droneseta-E-commerce-backend#8]

**Comment by GustavoRosaLemos** [comment]
@Mateus-Gabardo @danielkluggy 
O Swagger foi adicionado no projeto, para utilizar basta colocar a url: `localhost:8080/swagger-ui/#/`.


![Image](https://user-images.githubusercontent.com/46227839/224504179-ecc0faa8-ee4b-433c-b7a2-9a7c10e038db.png)
